import { useEffect, useState } from 'react'
import clsx from 'clsx'

interface ColDef { name: string; type: string }
interface DiffField { before: unknown; after: unknown; added?: boolean }
interface DataViewResult {
 table: string
 dataset_id: string
 columns: ColDef[]
 source_rows: Record<string, unknown>[]
 transformed_rows: Record<string, unknown>[]
 anomalies: Record<string, unknown>[]
 diffs: Record<string, DiffField>[]
 stats: Record<string, number>
 total_source: number
}

const TABLE_INFO: Record<string, { fhir: string; explanation: string }> = {
 members: { fhir: 'Patient', explanation: 'Member records become Patient resources.' },
 eligibility: { fhir: 'Coverage', explanation: 'Eligibility rows become Coverage resources.' },
 claims: { fhir: 'Claim', explanation: 'Claims become Claim resources.' },
}

function TablePanel({ title, rows }: { title: string; rows: Record<string, unknown>[] }) {
 if (!rows?.length) return <div className="rounded-2xl border border-slate-200 bg-white p-4 text-slate-500 shadow-sm">No rows available.</div>
 const cols = Object.keys(rows[0]).slice(0, 6)
 return (
 <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden shadow-sm">
 <div className="px-4 py-3 border-b border-slate-200 text-sm font-semibold text-slate-900 bg-slate-50">{title}</div>
 <div className="overflow-x-auto">
 <table className="w-full text-xs">
 <thead><tr className="bg-slate-50">{cols.map(c => <th key={c} className="text-left px-3 py-2 text-slate-500 font-mono">{c}</th>)}</tr></thead>
 <tbody>{rows.slice(0, 8).map((row, i) => <tr key={i} className={i % 2 === 0 ? 'bg-slate-50/60' : ''}>{cols.map(c => <td key={c} className="px-3 py-2 text-slate-700 font-mono max-w-[160px] truncate">{row[c] == null ? 'null' : String(row[c])}</td>)}</tr>)}</tbody>
 </table>
 </div>
 </div>
 )
}

export default function DataView({ runId, datasetName }: { runId: string; datasetName: string }) {
 const [activeTable, setActiveTable] = useState<'members' | 'eligibility' | 'claims'>('claims')
 const [data, setData] = useState<DataViewResult | null>(null)
 const [loading, setLoading] = useState(false)

 useEffect(() => {
 setLoading(true)
 fetch(`/api/runs/${runId}/data-view?table=${activeTable}&limit=15`).then(r => r.json()).then(d => { setData(d); setLoading(false) }).catch(() => setLoading(false))
 }, [runId, activeTable])

 const info = TABLE_INFO[activeTable]

 return (
 <div className="flex flex-col h-full overflow-hidden bg-slate-100">
 <div className="px-5 py-4 border-b border-slate-200 shrink-0 bg-white">
 <div className="flex items-center justify-between gap-4">
 <div>
 <h2 className="text-xl font-bold text-slate-900">Final Results</h2>
 <p className="text-slate-500 text-sm mt-1">{datasetName} — compare source input and transformed output in tabular form.</p>
 </div>
 <div className="flex items-center gap-2">
 {(['members', 'eligibility', 'claims'] as const).map(t => <button key={t} onClick={() => setActiveTable(t)} className={clsx('px-3 py-1.5 rounded-xl text-sm border transition-all', activeTable === t ? 'border-blue-200 bg-blue-50 text-blue-700' : 'border-slate-300 text-slate-600 bg-white hover:bg-slate-50')}>{t} {'->'} {TABLE_INFO[t].fhir}</button>)}
 </div>
 </div>
 </div>
 <div className="flex-1 overflow-y-auto p-5 space-y-5 bg-slate-50/50">
 {loading ? <div className="flex items-center justify-center h-full text-slate-500">Loading final results...</div> : !data ? <div className="text-slate-500">Failed to load results.</div> : <>
 <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
 <div className="text-slate-900 font-bold text-2xl">{activeTable} {'->'} {info.fhir}</div>
 <div className="text-slate-500 text-sm mt-2">{info.explanation}</div>
 <div className="grid grid-cols-3 gap-4 mt-5">
 <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[11px] uppercase tracking-wider text-slate-500 font-semibold mb-2">Input</div><div className="text-sm text-slate-700">Source PostgreSQL rows before conversion.</div></div>
 <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[11px] uppercase tracking-wider text-slate-500 font-semibold mb-2">Transformation</div><div className="text-sm text-slate-700">Values are mapped and reshaped into healthcare resource structure.</div></div>
 <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="text-[11px] uppercase tracking-wider text-slate-500 font-semibold mb-2">Output</div><div className="text-sm text-slate-700">FHIR-ready rows generated by the pipeline.</div></div>
 </div>
 </div>
 <div className="grid grid-cols-2 gap-5">
 <TablePanel title="Source Input Table" rows={data.source_rows} />
 <TablePanel title="Transformed Output Table" rows={data.transformed_rows} />
 </div>
 <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden shadow-sm">
 <div className="px-4 py-3 border-b border-slate-200 text-sm font-semibold text-slate-900 bg-slate-50">Changed Fields</div>
 <pre className="p-4 text-xs text-slate-700 overflow-x-auto whitespace-pre-wrap">{JSON.stringify(data.diffs, null, 2)}</pre>
 </div>
 {data.anomalies?.length > 0 && <div className="rounded-2xl border border-amber-200 bg-amber-50 overflow-hidden shadow-sm"><div className="px-4 py-3 border-b border-amber-200 text-sm font-semibold text-amber-700">Anomalies</div><pre className="p-4 text-xs text-amber-900 overflow-x-auto whitespace-pre-wrap">{JSON.stringify(data.anomalies, null, 2)}</pre></div>}
 </>}
 </div>
 </div>
 )
}
